services:
  - type: static_site
    name: gem-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 22.x
